### ISSUE TITLE
error compiling cython file

### ISSUE THREAD

**Issue by 986164283** [jyjblrd/Low-Cost-Mocap#32]
hello
I got an error when I try to install python setup.py install. I'm on Ubuntu 22. the main error:

Error compiling Cython file:
------------------------------------------------------------
...
        # init context
        print("about to init")
        try:
            ps3eye_init()
        except Exception as exc:
            print exc
                  ^
------------------------------------------------------------

pseyepy/cameras.pyx:245:18: Syntax error in simple statement list
Traceback (most recent call last):
  File "/root/pseyepy-master/setup.py", line 76, in <module>
    ext_modules=cythonize(extensions),)
                ^^^^^^^^^^^^^^^^^^^^^
  File "///anaconda3/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
    cythonize_one(*args)
  File "//anaconda3/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: pseyepy/cameras.pyx

The above is where the error is reported

I hope someone can help  and give me more information

Thanks in advance.

**Comment by jyjblrd** [comment]
Hi, that seems to be a bug in the pseyepy library: github.com/bensondaled/pseyepy/

Something is going wrong in the `ps3eye_init()` function and the exception isnt being printed because it should be `print(exc)` not `print exc`. I would change this line so you actually can see what the error is to properly debug the problem, and then reinstall the library.

**Comment by jyjblrd** [comment]
This issue looks to be the same issue that you had: [https://github.com/bensondaled/pseyepy/issues/15](https://github.com/bensondaled/pseyepy/issues/15)

**Comment by 986164283** [comment]
Hi, have you modified it? I downloaded and reinstalled and still got the same prompt。

**Comment by jyjblrd** [comment]
Hi, you should reinstall the pseyepy library, modify the code as I mentioned, and try run it again. Or you could pull [this branch](https://github.com/bensondaled/pseyepy/pull/18) which looks to solve the problem.

**Comment by 986164283** [comment]
Hello, after following the modifications you mentioned, the problem has been solved, thank you.


林玮
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jyjblrd/Low-Cost-Mocap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月15日(星期一) 晚上10:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jyjblrd/Low-Cost-Mocap] error compiling cython file (Issue #32)





 
Hi, you should reinstall the pseyepy library, modify the code as I mentioned, and try run it again. Or you could pull this branch which looks to solve the problem.

**Comment by luislglp** [comment]
Thanks for mentioning the checklist, jyjblrd.
I still had some issues with the pseyepy library even after following zalo's checklist to install on Windows 11 (VS 2022).
Maybe this is too basic, but not sure if we need somehow to install the camera drivers first.
I downloaded the CL-Eye driver, tested the cameras and after that the pseyepy library worked fine.
