### ISSUE TITLE
ESP32 code is for CP2104 or CH9102 ?

### ISSUE THREAD

**Issue by clennpillo** [jyjblrd/Low-Cost-Mocap#38]
hello, when I choose to buy ESP32 board, I found the link given in the article didn't specify the serial port type, say there are two types in the link, CP2104 and CH9102, which one should I buy ?

thanks .

**Comment by jyjblrd** [comment]
It shouldn't matter, those are just the usb --> uart chips they use. Both should work exactly the same.

**Comment by clennpillo** [comment]
thanks for the reply.
