### ISSUE TITLE
Operating System and Version Inquiry Regarding Compatibility Issues with Pseyepy Library

### ISSUE THREAD

**Issue by cultist123** [jyjblrd/Low-Cost-Mocap#40]
May I ask if you are using Ubuntu or Windows system, and what version? Your tutorial does not provide this information. The pseyepy library is very old, causing many backend configuration mismatches and incompatibilities, which has consumed a lot of my time.

**Comment by jyjblrd** [comment]
Hi, I am using MacOS 14. Pseyepy worked for me, but it might have some issues with Windows.

**Comment by cultist123** [comment]
I am also using macOS 14, but I have an M2 chip with ARM architecture. Are you using an Intel chip? I'm not sure if this will affect the project.

**Comment by jyjblrd** [comment]
I am also using a M2 Mac.

**Comment by cultist123** [comment]
That's great, thank you! I'll go and try it again.
