### ISSUE TITLE
Battery 9A seems way too big for the boards

### ISSUE THREAD

**Issue by clennpillo** [jyjblrd/Low-Cost-Mocap#43]
hi,

I found 9A battery is too big for the boards, already ruined ESP32 receiver, and F3 EVO is very hot while working, I'm not sure if I had done it right though.

**Comment by jyjblrd** [comment]
The battery shouldn't be blowing up your boards.
I connected the battery to the F3 EVO flight controller, and used the 3.3v output from that board to power the ESP32.

Perhaps you installed the battery with the wrong polarity (ie. mixed up +/-).. There is no protection against this and even doing it once can destroy the boards.

**Comment by clennpillo** [comment]
Maybe you're right, anyway I just used a smaller battery that is 1A, hope it works well.

**Comment by jyjblrd** [comment]
Amperage does not have any impact on if a battery will blow up a board, it's the voltage that kills a board. Single cell Li-ion batteries are always around 3.7v (because of chemistry), which the flight controller is built to handle.

The amp-hour (Ah) rating of a battery is just how long it will last. It's like how putting a larger fuel tank in your car won't damage the engine... if that makes sense. 

Just don't reverse the polarity and you'll be fine.

**Comment by clennpillo** [comment]
I guess my board blowed up was because I once reversed the polarity. I always think Amperage does not have any impact on if a battery will blow up a board, if I use 3.7V it's always ok.

one question is that why the battery has a paramter of 9A, what does this indicates ?

**Comment by jyjblrd** [comment]
The battery I recommend is the 18350 type (18mm * 35mm). The one I used has a voltage of 3.7v, a capacity of 1100mAh, and a max current if 9A. The voltage is self explanatory. 

1100mAh means that it can output 1100milliamps (at 3.7v) for 1 hour (this works out to 1.1Ah * 3.7v = 4.07watthours. 

9A means that the max current it can provide is 9 amps, or 9A*3.7V = 33.3 watts.

**Comment by clennpillo** [comment]
I used the 9A battery again, the F3 board was again much hotter than the small battery, I then found this picture below in your video, it showed that you used two resistances on the board, is this the reason that the current on your board is not that high.

<img width="711" alt="image" src="https://github.com/jyjblrd/Low-Cost-Mocap/assets/19600126/bbbd15be-70d0-4aef-b841-df6d4b19b874">

**Comment by jyjblrd** [comment]
No, those resistors are a voltage divider to measure the voltage level of the battery (which I never wrote the code for). 

After reversing the polarity of the F3 board, it will be permanently damaged, you may need to buy a new one.
